export const tools = [
    // PDF Tools
    { id: 'pdf-merge', name: 'Merge PDF', category: 'pdf', url: 'tools/pdf/merge.html', description: 'Combine multiple PDFs into one.', icon: 'fas fa-file-pdf', color: '#e74c3c', keywords: 'join binder combine' },
    { id: 'pdf-split', name: 'Split PDF', category: 'pdf', url: 'tools/pdf/split.html', description: 'Separate PDF pages.', icon: 'fas fa-cut', color: '#e74c3c', keywords: 'cut separate page' },
    { id: 'pdf-compress', name: 'Compress PDF', category: 'pdf', url: 'tools/pdf/compress.html', description: 'Reduce PDF file size.', icon: 'fas fa-compress-arrows-alt', color: '#e74c3c', keywords: 'shrink size optimize' },
    { id: 'pdf-conv-img', name: 'PDF to Image', category: 'pdf', url: 'tools/pdf/pdf-to-img.html', description: 'Convert pages to JPG/PNG.', icon: 'fas fa-image', color: '#e74c3c', keywords: 'convert jpg png' },
    { id: 'pdf-conv-pdf', name: 'Image to PDF', category: 'pdf', url: 'tools/pdf/img-to-pdf.html', description: 'Convert images to PDF.', icon: 'fas fa-file-image', color: '#e74c3c', keywords: 'create make photos' },
    { id: 'pdf-watermark', name: 'Watermark PDF', category: 'pdf', url: 'tools/pdf/watermark.html', description: 'Add text/image stamp.', icon: 'fas fa-stamp', color: '#e74c3c', keywords: 'stamp logo protect' },
    { id: 'pdf-duplicate', name: 'Duplicate Pages', category: 'pdf', url: 'tools/pdf/duplicate.html', description: 'Clone specific pages.', icon: 'fas fa-copy', color: '#e74c3c', keywords: 'clone repeat' },
    { id: 'pdf-rotate', name: 'Rotate PDF', category: 'pdf', url: 'tools/pdf/rotate.html', description: 'Rotate pages 90/180 deg.', icon: 'fas fa-sync-alt', color: '#e74c3c', keywords: 'turn orientation' },
    { id: 'pdf-delete', name: 'Delete Pages', category: 'pdf', url: 'tools/pdf/delete.html', description: 'Remove unwanted pages.', icon: 'fas fa-trash-alt', color: '#e74c3c', keywords: 'remove cut' },
    { id: 'pdf-extract', name: 'Extract Pages', category: 'pdf', url: 'tools/pdf/extract.html', description: 'Save specific pages.', icon: 'fas fa-file-export', color: '#e74c3c', keywords: 'save separate' },
    { id: 'pdf-reorder', name: 'Reorder PDF', category: 'pdf', url: 'tools/pdf/reorder.html', description: 'Rearrange page order.', icon: 'fas fa-sort', color: '#e74c3c', keywords: 'organize sort' },

    // Image Tools
    { id: 'img-compress', name: 'Compress Image', category: 'image', url: 'tools/image/compress.html', description: 'Shrink JPG/PNG/WEBP.', icon: 'fas fa-compress', color: '#3498db', keywords: 'shrink tiny optimize' },
    { id: 'img-editor', name: 'Photo Editor', category: 'image', url: 'tools/image/editor.html', description: 'Crop, Filter, Draw.', icon: 'fas fa-edit', color: '#3498db', keywords: 'photoshop modify adjust' },
    { id: 'img-resize', name: 'Resize Image', category: 'image', url: 'tools/image/resize.html', description: 'Change dimensions.', icon: 'fas fa-expand', color: '#3498db', keywords: 'scale dimension' },
    { id: 'img-convert', name: 'Convert Image', category: 'image', url: 'tools/image/convert.html', description: 'Switch format (JPG/PNG).', icon: 'fas fa-exchange-alt', color: '#3498db', keywords: 'format switch' },
    { id: 'img-crop', name: 'Crop Image', category: 'image', url: 'tools/image/crop.html', description: 'Cut specific area.', icon: 'fas fa-crop', color: '#3498db', keywords: 'cut trim' },
    { id: 'img-filters', name: 'Image Filters', category: 'image', url: 'tools/image/filters.html', description: 'Apply effects.', icon: 'fas fa-magic', color: '#3498db', keywords: 'sepia bw effect' },
    { id: 'img-meme', name: 'Meme Generator', category: 'image', url: 'tools/image/meme-generator.html', description: 'Create funny memes.', icon: 'fas fa-laugh-squint', color: '#3498db', keywords: 'caption text funny' },
    { id: 'img-color', name: 'Color Extractor', category: 'image', url: 'tools/image/color-extractor.html', description: 'Get colors from image.', icon: 'fas fa-palette', color: '#3498db', keywords: 'picker hex' },
    { id: 'img-bg', name: 'BG Remover', category: 'media', url: 'tools/media/bg-remover.html', description: 'Remove backgrounds AI.', icon: 'fas fa-eraser', color: '#e91e63', keywords: 'transparent remove background' },

    // Text Tools
    { id: 'txt-counter', name: 'Word Counter', category: 'text', url: 'tools/text/counter.html', description: 'Count words & chars.', icon: 'fas fa-calculator', color: '#2ecc71', keywords: 'length stats' },
    { id: 'txt-case', name: 'Text Modifier', category: 'text', url: 'tools/text/modifier.html', description: 'Case, Sort, Clean.', icon: 'fas fa-text-height', color: '#2ecc71', keywords: 'upper lower title sort' },
    { id: 'txt-lorem', name: 'Lorem Ipsum', category: 'text', url: 'tools/text/lorem.html', description: 'Generate placeholder text.', icon: 'fas fa-paragraph', color: '#2ecc71', keywords: 'dummy text generator' },
    { id: 'txt-diff', name: 'Diff Checker', category: 'text', url: 'tools/dev/diff-checker.html', description: 'Compare two texts.', icon: 'fas fa-columns', color: '#2ecc71', keywords: 'compare difference changes' },
    { id: 'txt-tts', name: 'Text to Speech', category: 'text', url: 'tools/text/tts.html', description: 'Read text aloud.', icon: 'fas fa-volume-up', color: '#2ecc71', keywords: 'speak audio voice' },

    // Dev Tools
    { id: 'dev-json', name: 'JSON Formatter', category: 'dev', url: 'tools/dev/json-formatter.html', description: 'Prettify/Minify JSON.', icon: 'fas fa-code', color: '#f39c12', keywords: 'lint beautify' },
    { id: 'dev-regex', name: 'Regex Tester', category: 'dev', url: 'tools/dev/regex.html', description: 'Test regular expressions.', icon: 'fas fa-vial', color: '#f39c12', keywords: 'match pattern' },
    { id: 'dev-qr', name: 'QR Generator', category: 'dev', url: 'tools/qr/index.html', description: 'Create QR Codes.', icon: 'fas fa-qrcode', color: '#34495e', keywords: 'barcode scan' },
    { id: 'dev-barcode', name: 'Barcode Tools', category: 'dev', url: 'tools/barcode/index.html', description: 'Generate & Scan Barcodes.', icon: 'fas fa-barcode', color: '#34495e', keywords: 'upc ean scan' },
    { id: 'dev-markdown', name: 'Markdown Editor', category: 'dev', url: 'tools/markdown/editor.html', description: 'Write & Preview MD.', icon: 'fas fa-file-code', color: '#2c3e50', keywords: 'preview write' },
    { id: 'dev-hash', name: 'Hash Generator', category: 'dev', url: 'tools/dev/hash.html', description: 'MD5, SHA-256.', icon: 'fas fa-fingerprint', color: '#f39c12', keywords: 'crypto security' },
    { id: 'dev-base64', name: 'Base64 Encode', category: 'dev', url: 'tools/dev/base64.html', description: 'Encode/Decode text.', icon: 'fas fa-shield-alt', color: '#f39c12', keywords: 'convert string' },
    { id: 'dev-resume', name: 'Resume Builder', category: 'dev', url: 'tools/dev/resume-builder.html', description: 'Build CV with Markdown.', icon: 'fas fa-file-invoice', color: '#ff5722', keywords: 'cv job application' },
    { id: 'dev-zip', name: 'Archive Manager', category: 'dev', url: 'tools/archive/zip.html', description: 'Zip & Unzip files.', icon: 'fas fa-file-archive', color: '#f39c12', keywords: 'compress extract' },

    // Govt & Utility
    { id: 'govt-aadhaar', name: 'Aadhaar Tools', category: 'govt', url: 'tools/government/aadhaar.html', description: 'Compress/Clean Aadhaar.', icon: 'fas fa-id-card', color: '#9c27b0', keywords: 'uidai identity' },
    { id: 'govt-pan', name: 'PAN Tools', category: 'govt', url: 'tools/government/pan.html', description: 'Resize/Crop for PAN.', icon: 'fas fa-id-card-alt', color: '#9c27b0', keywords: 'tax id card' },
    { id: 'govt-photo', name: 'Passport Photo', category: 'govt', url: 'tools/government/passport-photo.html', description: 'Crop for official docs.', icon: 'fas fa-user-circle', color: '#9c27b0', keywords: 'india size visa' },
    { id: 'govt-exam', name: 'Exam Tools', category: 'govt', url: 'tools/government/exam.html', description: 'Prepare exam documents.', icon: 'fas fa-user-graduate', color: '#9c27b0', keywords: 'student hall ticket' },
    { id: 'govt-kyc', name: 'KYC & Jobs', category: 'govt', url: 'tools/government/kyc.html', description: 'Prepare job documents.', icon: 'fas fa-briefcase', color: '#9c27b0', keywords: 'application resume' },
    { id: 'govt-sig', name: 'Signature Pad', category: 'govt', url: 'tools/government/signature.html', description: 'Draw e-signature.', icon: 'fas fa-signature', color: '#9c27b0', keywords: 'sign draw png' },
    { id: 'govt-age', name: 'Age Calculator', category: 'govt', url: 'tools/government/age-calculator.html', description: 'Calculate exact age.', icon: 'fas fa-birthday-cake', color: '#9c27b0', keywords: 'dob years months' },
    { id: 'govt-resize', name: 'KB Resizer', category: 'govt', url: 'tools/government/kb-resizer.html', description: 'Resize to target KB.', icon: 'fas fa-compress-arrows-alt', color: '#9c27b0', keywords: 'size compress' },
    { id: 'govt-jpg2pdf', name: 'JPG to PDF', category: 'govt', url: 'tools/government/jpg-to-pdf.html', description: 'Convert images to PDF.', icon: 'fas fa-file-pdf', color: '#9c27b0', keywords: 'convert image document' },
    { id: 'util-wifi', name: 'Wi-Fi QR', category: 'utility', url: 'tools/utility/wifi-qr.html', description: 'Share Wi-Fi easily.', icon: 'fas fa-wifi', color: '#9c27b0', keywords: 'network internet' },
    { id: 'util-encrypt', name: 'The Vault', category: 'utility', url: 'tools/utility/encrypt.html', description: 'Encrypt files securely.', icon: 'fas fa-lock', color: '#2c3e50', keywords: 'secure aes private' },
    { id: 'util-kanban', name: 'Kanban Board', category: 'utility', url: 'tools/productivity/kanban.html', description: 'Manage tasks offline.', icon: 'fas fa-columns', color: '#27ae60', keywords: 'todo plan project' },
    { id: 'util-screen', name: 'Screen Recorder', category: 'media', url: 'tools/media/screen-recorder.html', description: 'Record screen & mic.', icon: 'fas fa-video', color: '#e91e63', keywords: 'capture video' },
    { id: 'util-voice', name: 'Voice Recorder', category: 'media', url: 'tools/media/voice-recorder.html', description: 'Record audio/mp3.', icon: 'fas fa-microphone', color: '#e91e63', keywords: 'sound mic' },
    { id: 'util-audio', name: 'Audio Trimmer', category: 'media', url: 'tools/media/audio-trimmer.html', description: 'Cut MP3/WAV files.', icon: 'fas fa-cut', color: '#e91e63', keywords: 'music sound edit' },
    { id: 'util-converter', name: 'Unit Converter', category: 'utility', url: 'tools/dev/unit-converter.html', description: 'Convert length, weight, currency.', icon: 'fas fa-exchange-alt', color: '#8e44ad', keywords: 'calc measure' },
    { id: 'util-timer', name: 'Stopwatch & Timer', category: 'utility', url: 'tools/dev/timer.html', description: 'Track time accurately.', icon: 'fas fa-stopwatch', color: '#e74c3c', keywords: 'clock alarm' },

    // Fun & Games
    { id: 'game-hub', name: 'Game Arcade', category: 'fun', url: 'games/index.html', description: 'Play offline games.', icon: 'fas fa-gamepad', color: '#ffeb3b', keywords: 'play fun 2048' },
    { id: 'fun-decision', name: 'Decision Wheel', category: 'fun', url: 'tools/fun/wheel.html', description: 'Spin the wheel.', icon: 'fas fa-dharmachakra', color: '#ffeb3b', keywords: 'random choice' },
    { id: 'fun-paint', name: 'Paint', category: 'fun', url: 'tools/fun/paint.html', description: 'Draw and sketch.', icon: 'fas fa-paint-brush', color: '#ffeb3b', keywords: 'draw art canvas' },
    { id: 'fun-dice', name: 'Dice Roller', category: 'fun', url: 'tools/fun/dice.html', description: 'Roll 3D dice.', icon: 'fas fa-dice', color: '#ffeb3b', keywords: 'dnd random rng' },
    { id: 'fun-coin', name: 'Coin Flip', category: 'fun', url: 'tools/fun/coin.html', description: 'Flip a coin.', icon: 'fas fa-coins', color: '#ffeb3b', keywords: 'heads tails random' },
    { id: 'fun-emoji', name: 'Emoji Picker', category: 'fun', url: 'tools/fun/emoji.html', description: 'Find & copy emojis.', icon: 'fas fa-smile', color: '#ffeb3b', keywords: 'search faces' },
    { id: 'fun-ascii', name: 'ASCII Art', category: 'fun', url: 'tools/fun/ascii.html', description: 'Convert text to ASCII.', icon: 'fas fa-hashtag', color: '#ffeb3b', keywords: 'code art' },
    { id: 'fun-zalgo', name: 'Zalgo Text', category: 'fun', url: 'tools/fun/zalgo.html', description: 'Generate glitch text.', icon: 'fas fa-bug', color: '#ffeb3b', keywords: 'cursed mess' },
    { id: 'fun-team', name: 'Team Generator', category: 'fun', url: 'tools/fun/team.html', description: 'Randomize groups.', icon: 'fas fa-users', color: '#ffeb3b', keywords: 'groups teams' },
    { id: 'fun-reaction', name: 'Reaction Test', category: 'fun', url: 'tools/fun/reaction.html', description: 'Test multiple reflexes.', icon: 'fas fa-bolt', color: '#ffeb3b', keywords: 'speed game' },
    { id: 'fun-list', name: 'List Shuffler', category: 'fun', url: 'tools/fun/list.html', description: 'Randomize lists.', icon: 'fas fa-list-ol', color: '#ffeb3b', keywords: 'sort random' },
];
